---
- hosts: k8s_cluster
  become: true
  gather_facts: true
  vars:
    kubernetes_version: "1.31.0"
    kubernetes_apt_repository: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.31/deb/ /"
  tasks:
    - name: 顯示正在處理的主機
      debug:
        msg: "正在處理 Kubernetes 節點: {{ inventory_hostname }} ({{ ansible_host }})"

    - name: 檢查 apt 鎖狀態
      shell: lsof /var/lib/apt/lists/lock /var/lib/dpkg/lock /var/lib/dpkg/lock-frontend /var/cache/apt/archives/lock 2>/dev/null || echo "No locks"
      register: apt_locks
      changed_when: false
      ignore_errors: yes

    - name: 顯示 apt 鎖狀態
      debug:
        var: apt_locks.stdout_lines
      when: apt_locks.stdout != "No locks"

    - name: 創建 Kubernetes APT 密鑰目錄
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: 下載 Kubernetes APT 密鑰
      get_url:
        url: https://pkgs.k8s.io/core:/stable:/v1.31/deb/Release.key
        dest: /tmp/k8s-apt.key
        mode: '0644'

    - name: 添加 Kubernetes APT 密鑰
      shell: cat /tmp/k8s-apt.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
      args:
        creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

    - name: 添加 Kubernetes APT 倉庫
      apt_repository:
        repo: "{{ kubernetes_apt_repository }}"
        state: present
        filename: kubernetes
        update_cache: yes

    - name: 安裝 Kubernetes 套件
      shell: >
        DEBIAN_FRONTEND=noninteractive apt-get update && 
        DEBIAN_FRONTEND=noninteractive apt-get install -y 
        kubelet={{ kubernetes_version }}-* 
        kubeadm={{ kubernetes_version }}-* 
        kubectl={{ kubernetes_version }}-*
      register: k8s_install
      retries: 3
      delay: 5
      until: k8s_install is success

    - name: 顯示 Kubernetes 安裝結果
      debug:
        var: k8s_install.stdout_lines
      when: k8s_install.stdout_lines is defined

    - name: 鎖定 Kubernetes 套件版本
      dpkg_selections:
        name: "{{ item }}"
        selection: hold
      with_items:
        - kubelet
        - kubeadm
        - kubectl

    - name: 啟用 kubelet 服務
      systemd:
        name: kubelet
        daemon_reload: yes
        enabled: yes 